serviceUrl:
          defaultZone: http://localhost:8761/eureka/
                    instance:
                   hostname: localhost
   
spring:
  application:
    name: DEMO-EUREKA-ORDER
      
    
    
     